- .gitignore
- client/Caddyfile
- docker/nginx.conf
- docker/staging/Dockerfile-client
- docker/staging/Dockerfile-server
- docker/staging/docker-compose.yml
> ステージング環境用のDockerfileを書いた

- .circleci/config.yml
- README.md
masterブランチにpushされるとステージング環境にデプロイされるようにした
ついでにREADMEにバッジが表示されるようにした
Close #8
> Circle CIでデプロイできるようにした

- .circleci/config.yml
- client/src/router.js
> CircleCIにclientのlintを導入した

- model/comments.go
- model/items.go
- model/likemaps.go
- model/logs.go
- model/ownershipmaps.go
- model/tagmaps.go
- model/tags.go
- model/users.go
gormわかんなくてnot nullとか書いてない(users.goを参考にした)のと、カラムと対応しているところの型の宣言がこれでいいのかわかんないです
> MDをみながら構造体(type ~ struct{~})だけ書きました

- model/comments_test.go
- model/items_test.go
- model/likemaps_test.go
- model/logs_test.go
- model/ownershipmaps_test.go
- model/tagmaps.go
- model/tagmaps_test.go
- model/tags_test.go
ほかの言語でもテストを書いたことないのでコピペ以外何もできません
勉強しときます
> とりあえずコピペだけしました

- model/users.go
- model/users_test.go
> とりあえず書いてみたけどダメそう(特にテスト)

- model/users.go
- model/users_test.go
- router/router.go
- router/users.go
怪しいところはrouterのreqの型定義(よくわからなかったから適当にしてしまった)
testも書こうと思ったけどmiddleware.goに手を出す必要がありそうだったので避けました
swaggerも書こうとしたんですがエラーが治せず諦めました
> routerのPUT /usersの追加、modelのUpdateUserとそのテストの修正をしました

- model/items.go
- model/items_test.go
- router/items.go
- router/router.go
> POST /items の実装

- router/users_test.go
実は #35 を検証しながらテストを作成していました
とりあえず権限を持つユーザーは変更できること、権限を持たないユーザーは403エラーが返ってくることをテストしました
> PUT /users のテスト追加

- README.md
- scripts/build.sh
- scripts/new_task.sh
- scripts/staging_deploy.sh
- scripts/test.sh
- scripts/up.sh
開発便利コマンド集みたいなものです
`$ sh scripts/up.sh`で開発環境が起動できるようになります
ただ、Windowsで動くかどうかは環境次第です
Close #33
> 開発用コマンドショートカットを追加

- client/package-lock.json
- docs/schema.md
- model/db.go
- model/items.go
- model/users.go
- model/users_test.go
- router/items.go
- router/items_test.go
- router/users.go
- router/users_test.go
item.typeでAdmin判定をすっかり忘れてたのでそれも追加しました.
> PostItemsのテストを追加しました.

- Dockerfile
- model/db.go
- model/items.go
- model/items_test.go
- router/items.go
- router/items_test.go
> ownerの登録に関するテストの追加

- client/package.json
- client/src/components/AdminPage.vue
- client/src/components/AllItemPage.vue
- client/src/components/ItemDetailPage.vue
- client/src/components/RegisterItemPage.vue
- client/src/components/RegisterOwnerForm.vue
- client/src/components/RentalForm.vue
- client/src/components/core/SideBar.vue
- client/src/components/shared/Icon.vue
- client/src/components/shared/ItemList.vue
Close #86 
CircleCIがlintを素通りする状態だったのでそれの修正とファイル群の修正をやりました
> client-lintを修正

- client/src/components/core/NavBar.vue
- client/src/components/core/SideBar.vue
- client/src/router.js
Close #91
バグの原因は以下のリンクらへんだった
https://router.vuejs.org/ja/api/#active-class
バグを修正してついでにAbout(下の？マーク)を配置したりしました
> サイドバーのリンクを修正

- client/src/components/RegisterItemPage.vue
- model/db.go
- router/items.go
サーバー側の関数が何やってるかよくわからなかったから書き替えました(いったい誰が書いたんだ...)
> RegisterItemPageの実装

- client/src/components/AllItemPage.vue
- client/src/components/core/View.vue
- client/src/components/shared/ItemList.vue
クリックしたら詳細ページに飛べるところまで
ownerの状態管理はまだ
> ItemListの実装

- docs/schema.md
- docs/swagger.yml
- model/items.go
swagger分からんマンです
ownerのgormのとこにnot null を追加しました
> swaggerの修正です

- model/comments.go
- model/db.go
- router/items.go
- router/router.go
servertestしていないのでryoha君にお願いします。
> server comment 機能追加

- model/comments.go
pull requestを忘れていました。ご迷惑おかけしてすみません。
> fix uint int

- client/src/components/UserPage.vue
> UserPageの実装

- model/items.go
- model/logs.go
- model/logs_test.go
> LogsからLatestLogsを生成するロジック

- client/src/components/shared/ReturnForm.vue
Close #184 
手元にUserが複数いないのでテストできていません
> 借りてない状態でも返却できる問題のクライアント側

- client/vue.config.js
これでうまくいってるのか？(Macだからわからず)
だれかこのブランチに入って試してみて欲しいです
> Windows版の開発環境でホットリロードがされない問題の修正

- model/items.go
そういえばRentalUserのCountは基本負の値で最大でも０っていう話をだれにもしてなかった気がするな...
> 借りてなくても返せる　SideS(erver)

- client/src/components/shared/RentalForm.vue
- client/src/components/shared/ReturnForm.vue
なぜかエラーキャッチのところで`return`なり`return false`なりしてもそこで関数が終わってくれなかった＞＜
Close #192
> 借りるor返すのに失敗したのにtraQに送信される

- router/middleware.go
> Admin設定を消した

- client/src/components/ItemListPage.vue
- client/src/components/core/SideBar.vue
- client/src/router.js
All Itemは廃止しました(一応URL叩くと見られる)
鯖側じゃなくてクライアント側で処理してしまった(本当は鯖側でフィルタリングするのが良い)
Close #170
> All Itemリストを備品と個人のものに分けた

- client/src/components/DashBoard.vue
- client/src/components/shared/ItemList.vue
- client/src/store.js
別にDashBoardでも解消されてなかったのでそっちも解消しました
Close #167
> まとめて借りるとき同じアイテムを借りると借りれる上限を超える

- client/src/components/DashBoard.vue
- client/src/version.js
- router/items.go
> rentalのクエリパラメータundefined問題

- model/items.go
gmコード書いてた><
言い訳すると「これで動いたら俺もうコード書くのやめるわｗ」って思ってたコードを一応動くか確認するか...と思ったら動いたというあれです
> itemsをとってくるタイプのクエリ改善

- model/items.go
- model/items_test.go
- model/logs_test.go
- router/items_test.go
- router/logs.go
- router/logs_test.go
まだWIPです
modelの方は１つを残して終わりました
Close #206
> サーバーのテストの追加

- client/src/components/core/NavBar.vue
- client/src/components/shared/RentalForm.vue
- client/src/components/shared/ReturnForm.vue
> traQ message with purpose

- client/src/components/ItemDetailPage.vue
- client/src/components/shared/WannaRental.vue
> 借りたいボタンを押したらその人にDMが送れるように

- client/src/components/AdminPage.vue
- client/src/router.js
- model/users.go
- model/users_test.go
Close #187 
管理者ならAdminページから権限をいじれるようになりました
デザインはくそ適当です
> Adminページの実装

- client/src/components/BarCode.vue
- client/src/components/RegisterItemPage.vue
> barcodeが閉じるように

- client/package-lock.json
- client/package.json
Close #210
手元ではカレンダーだけ確認済み
他のページの動作確認はステージング環境でいいすか
> カレンダーのXSS修正(Vuetifyアップデート)

- client/package-lock.json
- client/package.json
Reverts traPtitech/booQ#235
バーコード機能に不具合が出たのでいったん元のバージョンに戻す
> Revert "カレンダーのXSS修正(Vuetifyアップデート)"

- client/package-lock.json
- client/package.json
- client/src/components/BarCode.vue
- client/src/components/shared/Dialog.vue
> Vuetifyアップデート & バーコードの表示が崩れる問題の修正

- client/src/components/ItemDetailPage.vue
- client/src/components/ItemListPage.vue
- client/src/components/UserPage.vue
- client/src/components/core/NavBar.vue
- client/src/store.js
> ページごとに適切なタイトルになるように変更

- client/src/components/ItemDetailPage.vue
- client/src/components/shared/EditOwner.vue
- model/items.go
- model/items_test.go
- router/items.go
- router/items_test.go
- router/router.go
> 所有者の個数を減らす機能の追加

- model/items.go
Close #258 
適当なコミットメッセージで出しちゃったのでコミットしなおします
> RentalUserのOwnerが空だった問題の解決

- client/public/index.html
> HTMLの言語設定を日本語に

- router/router.go
Close #261 
以下は初めて見る人用の文章
これは認証をtokenでやっているからおこっている
cookieなら解消される
[ここ](https://github.com/traPtitech/booQ/blob/16ce45e7be179c1c5fbb463153716cd28e3398a1/router/middleware.go#L34)以下をcookieでの認証にすればいいと思う
その辺は分からんかったからやってない
> GET /api/files/:idを認証なしに

- client/src/components/ItemDetailPage.vue
- client/src/components/shared/EditOwner.vue
- model/items.go
> EditOwnerのKAIZEN

- client/src/components/DashBoard.vue
> ダッシュボードにリンクを置く

- client/src/components/shared/ReturnForm.vue
> アイテムを減らしたあと返せないバグの解決

- .github/workflows/release.yaml
`v～`タグをpushするとGitHubActionsでビルドされてGitHubPackagesに`v～`で登録されるようにしました
よろしくお願いします
> GitHub Actionsでイメージをビルドするように

- client/src/components/ItemDetailPage.vue
- client/src/components/shared/CommentDialog.vue
> コメント投稿時にtraQにも投稿

- client/src/components/core/SideBar.vue
> 検索を紫から緑に fix #288

- client/src/components/ItemDetailPage.vue
- client/src/components/shared/RentalForm.vue
> 貸し出し可能数が０のとき借りれないように

- client/src/components/ItemListPage.vue
#175 
ItemListPageに検索バーを追加しました。検索機能はサイドバーのものを流用しました。
> add search-bar

- model/db.go
> BlockGlobalUpdate

- client/src/components/ItemDetailPage.vue
> いいねアイコンの幅を狭くした

- docker/production/Dockerfile
Node.jsのイメージでクライアントのビルドを行うようにしました。
Close #373
> 本番環境用DockerfileでNode.jsのイメージを使うように

- client/src/components/shared/RentalForm.vue
- router/logs.go
> fix check type

- docs/swagger.yml
https://github.com/traPtitech/booQ-UI/pull/64#discussion_r471077232
追加した
> Add add/remove to LogType

- docs/swagger.yml
> ownerの構造体の変更

- .github/workflows/release.yaml
set-envは動かなくなったので変えています
ref
https://qiita.com/shonansurvivors/items/f256a0443d346f09448e
https://q.trap.jp/messages/afd64f82-04de-4263-931b-4f7717dee087
> Update deprecated workflow syntax

- model/items.go
- model/items_test.go
- router/items_test.go
> GetItemResponseを追加

- docs/swagger.yml
> `#/components/schemas/itemPosted/imgUrl`に`default`を追加
